// File generated by FlutterFire CLI.
// This is a placeholder - you need to run 'flutterfire configure' to generate the real file
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER - Replace with your actual Firebase config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-_mod0cWLLhIAnFQvOdnAWLXlL8RzFo',
    appId: '1:251282535668:web:c51f035d4c164e26bd1aa1',
    messagingSenderId: '251282535668',
    projectId: 'swiftretreat-c7fad',
    authDomain: 'swiftretreat-c7fad.firebaseapp.com',
    storageBucket: 'swiftretreat-c7fad.firebasestorage.app',
    measurementId: 'G-TQ8FPDXVZ0',
  );

  // Get this from Firebase Console: Project Settings > Your apps > Firebase SDK snippet

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf70Flxu_9NGf8X3fvHLzV30ykz0zJiro',
    appId: '1:251282535668:android:9b25fed1d70feab1bd1aa1',
    messagingSenderId: '251282535668',
    projectId: 'swiftretreat-c7fad',
    storageBucket: 'swiftretreat-c7fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FJ-OA9NCB-mqy1o2AbPqdFv0rdAY88M',
    appId: '1:251282535668:ios:01e1d04bbae57895bd1aa1',
    messagingSenderId: '251282535668',
    projectId: 'swiftretreat-c7fad',
    storageBucket: 'swiftretreat-c7fad.firebasestorage.app',
    iosBundleId: 'com.example.swiftretreat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0FJ-OA9NCB-mqy1o2AbPqdFv0rdAY88M',
    appId: '1:251282535668:ios:01e1d04bbae57895bd1aa1',
    messagingSenderId: '251282535668',
    projectId: 'swiftretreat-c7fad',
    storageBucket: 'swiftretreat-c7fad.firebasestorage.app',
    iosBundleId: 'com.example.swiftretreat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9-_mod0cWLLhIAnFQvOdnAWLXlL8RzFo',
    appId: '1:251282535668:web:dbccf7230a5fe45bbd1aa1',
    messagingSenderId: '251282535668',
    projectId: 'swiftretreat-c7fad',
    authDomain: 'swiftretreat-c7fad.firebaseapp.com',
    storageBucket: 'swiftretreat-c7fad.firebasestorage.app',
    measurementId: 'G-D32Y2FSEC2',
  );

}